### PR TITLE
Add support to Screensharing and h264 simulcast

### PR DESCRIPTION
**Pull request by jcague**
**Description**

There are new experimental features in Chrome that enable Simulcast for Screensharing and h.264 Streams. This PR fix some issues I found in the first tests I run.

[] It needs and includes Unit Tests

**Changes in Client or Server public APIs**

Not needed.

[] It includes documentation for these changes in `/doc`.

### CODE REVIEW

**Comment by kekkokk** [comment]
How did you enabled h264 simulcast in chrome?

**Comment by wangbing8895** [comment]
@jcague How did you enabled h264 simulcast in chrome?  it don't work.

**Comment by wangbing8895** [comment]
@kekkokk do you know how it works?

**Comment by kekkokk** [comment]
Nope, never had a response

**Comment by jcague** [comment]
sorry for the late answer, you have to enable it via a FieldTrial in the latest versions of Chrome (69+ I think). I tested it some weeks ago with Chrome Canary and this parameters:
`/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --force-fieldtrials=WebRTC-H264Simulcast/Enabled/`

**Comment by kekkokk** [comment]
thanks @jcague !

**Comment by wangbing8895** [comment]
@kekkokk Hi, I want to know why chrome 69 does not work,but Chrome Canary can work? 
It just because the webrtc version of chrome ?
Thanks!

**Comment by kekkokk** [comment]
I haven't tried yet, I'm really busy implementing new features right now. I'll let you know

**Comment by wangbing8895** [comment]
@jcague @kekkokk Does the latest chrome(74.0.3729.169) support H264 simulcast now? Canary chrome used to support H264 simulcast, but now cann't, why? In my experiment, I used wireshark to grab the packet to observe the ssrc of video.

**Pull request merged**
