### PR TITLE
[FEATURE-REVIEW] Updated Single PeerConnection 

### PR DESCRIPTION
**Pull request by lodoyun**
**Description**
Updates the feature review for Single PeerConnection with some of the new ideas for the design.

[] It needs and includes Unit Tests

**Changes in Client or Server public APIs**

[] It includes documentation for these changes in `/doc`.

### CODE REVIEW

**Comment by kekkokk** [comment]
It's not very clear to me how the single peerconnection is managed in terms of scalability. I mean, if there are 2 streams, on 2 different erizoJS, and I want to subscribe both in a single peerconnection, how this would work? 
Isn't something as erizo tree a prerequisite for this implementation? (also useful to maximize the scalability of licode)

**Comment by lodoyun** [comment]
@kekkokk In short, you wouldn't be able to subscribe to both with the same PeerConnection. 
The idea here is that the amount of ErizoJSs available for each room would be controlled by the policy. There's a tradeoff there that you could tweak for your application. If you absolutely need everyone with single PeerConnection, you will restrict them to the same process and server. That may work perfectly, depending on your needs.
Erizo trees would allow another level of control but I don't see it a prerequisite.

**Comment by kekkokk** [comment]
ok, makes sense

**Comment by notedit** [comment]
it will reduce lots of port use. look forward this feature,  is there any timeline for this?

**Comment by arsenicraghav** [comment]
@lodoyun Thank you updating the feature review document. Is this already implemented ? If not any timelines ?

**Pull request merged**
