### PR TITLE
Fix audio/video only streams with Firefox

### LINKED ISSUE #1466: Publish a Voice or Video Only Stream fails on Firefox
If I want to publish a voice or video only stream, Firefox will not do that. Error in the console of the browser: `InvalidAccessError: Answer tried to set recv when offer did not set send`

All working fine on Chrome or if I publish a Video with Voice combined!

Im on the latest commit, and testet with FF68 and 69

according to this: https://stackoverflow.com/questions/35166456/jssip-firefox-invalidsessiondescriptionerror-answer-tried-to-set-recv-when-of
--> Valid answers to a=recvonly are a=sendonly and a=inactive.

As you can see, the answer is: "sendrecv" at some point in the logs

````
DEBUG:  processAnswer - Remote Description answer v=0

o=- 0 0 IN IP4 127.0.0.1

s=LicodeMCU

t=0 0

a=msid-semantic: WMS *

a=group:BUNDLE 0 1

m=audio 9 UDP/TLS/RTP/SAVPF 109

c=IN IP4 0.0.0.0

a=rtpmap:109 opus/48000/2

a=rtcp:1 IN IP4 0.0.0.0

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=setup:active

a=mid:0

a=recvonly

a=ice-ufrag:f1ee11d2

a=ice-pwd:148ddc341c12a2b09f28720b7dc0c653

a=fingerprint:sha-256 53:9F:D1:42:DF:CF:64:0D:54:A2:CE:30:60:3C:BE:AF:06:23:31:2C:6C:05:D0:0C:2E:AC:71:72:1D:EA:05:A6

a=candidate:0 1 udp 2130444543 134.103.176.109 30042 typ host generation 0

a=end-of-candidates

a=rtcp-mux

m=video 9 UDP/TLS/RTP/SAVPF 120

c=IN IP4 0.0.0.0

a=rtpmap:120 VP8/90000/2

a=rtcp:1 IN IP4 0.0.0.0

a=rtcp-fb:120 ccm fir

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 goog-remb

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:5 urn:ietf:params:rtp-hdrext:toffset

a=setup:active

a=mid:1

a=recvonly

a=ice-ufrag:f1ee11d2

a=ice-pwd:148ddc341c12a2b09f28720b7dc0c653

a=fingerprint:sha-256 53:9F:D1:42:DF:CF:64:0D:54:A2:CE:30:60:3C:BE:AF:06:23:31:2C:6C:05:D0:0C:2E:AC:71:72:1D:EA:05:A6

a=candidate:0 1 udp 2130444543 134.103.176.109 30042 typ host generation 0

a=end-of-candidates

a=rtcp-mux

erizo.js:100:13
````

````
DEBUG:  processAnswer - Local Description answer v=0

o=mozilla...THIS_IS_SDPARTA-68.0.2 312677747841195524 0 IN IP4 0.0.0.0

s=-

t=0 0

a=fingerprint:sha-256 26:6A:83:69:13:0D:95:8D:23:C6:EE:2F:91:29:9E:93:39:29:C9:85:9C:FF:A0:E1:B1:0C:7D:EC:7F:78:10:62

a=ice-options:trickle

a=msid-semantic: WMS *

a=group:BUNDLE 0 1

m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101

c=IN IP4 0.0.0.0

a=rtpmap:109 opus/48000/2

a=rtpmap:9 G722/8000/1

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:101 telephone-event/8000/1

a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1

a=fmtp:101 0-15

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=extmap:2 urn:ietf:params:rtp-hdrext:csrc-audio-level

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=setup:actpass

a=mid:0

a=sendrecv

a=ice-ufrag:8aa6ae07

a=ice-pwd:204689354d132a616a608dcd7c7f5351

a=ssrc:1094494717 cname:{f84e9746-87e5-4496-8bde-0621234c817c}

a=ssrc:1094494717 msid:{0024819b-e2d7-4d6b-82c3-836bf914308d} {995f04f5-119f-4203-95a3-819a7c7c5db0}

a=rtcp-mux

m=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97

c=IN IP4 0.0.0.0

a=rtpmap:120 VP8/90000

a=rtpmap:121 VP9/90000

a=rtpmap:126 H264/90000

a=rtpmap:97 H264/90000

a=fmtp:120 max-fs=12288;max-fr=60

a=fmtp:121 max-fs=12288;max-fr=60

a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1

a=rtcp-fb:120 nack

a=rtcp-fb:120 nack pli

a=rtcp-fb:120 ccm fir

a=rtcp-fb:120 goog-remb

a=rtcp-fb:121 nack

a=rtcp-fb:121 nack pli

a=rtcp-fb:121 ccm fir

a=rtcp-fb:121 goog-remb

a=rtcp-fb:126 nack

a=rtcp-fb:126 nack pli

a=rtcp-fb:126 ccm fir

a=rtcp-fb:126 goog-remb

a=rtcp-fb:97 nack

a=rtcp-fb:97 nack pli

a=rtcp-fb:97 ccm fir

a=rtcp-fb:97 goog-remb

a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:5 urn:ietf:params:rtp-hdrext:toffset

a=setup:actpass

a=mid:1

a=recvonly

a=ice-ufrag:8aa6ae07

a=ice-pwd:204689354d132a616a608dcd7c7f5351

a=rtcp-mux

````

### PR DESCRIPTION
**Pull request by jcague**
**Description**

Fixes #1466 

Firefox expects an answer with a=inactive when there is no audio or video in an SDP negotiation.

[] It needs and includes Unit Tests

**Changes in Client or Server public APIs**

Not needed.

[] It includes documentation for these changes in `/doc`.

### CODE REVIEW

**Comment by cracker0dks** [comment]
can we get this merged please ? :)

**Comment by jcague** [comment]
@cracker0dks I'll do it as soon as I can test that it does not affect other parts of the code, sorry about the additional delay

**Comment by jcague** [comment]
@cracker0dks I'm afraid I won't test this PR enough before January, but feel free to merge it in your code temporarilly and test it in the mean time.

**Comment by cracker0dks** [comment]
ok, thanks, no problem, everyone is using chrome till then :)

**Pull request merged**
