### PR TITLE
Hack to avoid make sure we pass candidates in libnice even when there's only mdns

### PR DESCRIPTION
**Pull request by lodoyun**
**Description**

This PR introduces a hack to fix [this issue](https://gitlab.freedesktop.org/libnice/libnice/-/issues/69) until we can use an updated version of libnice with [this fix](https://gitlab.freedesktop.org/libnice/libnice/-/merge_requests/182).
In short, when connecting with Chrome and libnice with `ice-lite` there's a change we're not passing any remote candidates to libnice because they are mdns candidates and they are not valid. Instead of resolving those candidates (which may not always work), this hack just passes a "dummy" candidate to get libnice to progress to the next state.

[] It needs and includes Unit Tests

**Changes in Client or Server public APIs**

[] It includes documentation for these changes in `/doc`.

### CODE REVIEW

**Review by jcague — APPROVED** [review]
LGTM, it would be interesting to have reminders in GitHub to review hacks in the future

**Comment by ranthwar-vcloudx** [comment]
@lodoyun This fix is working only for chrome and Edge....FF and safari is breaking with this changes....Can you suggest us any alternative fix for safari and FF....

**Comment by lodoyun** [comment]
This is a problem specific to using libnice and, I've only been able to reproduce it with ice-lite.
How are you reproducing this? This is a pretty rare issue since, I've only seen it happen when both Licode and the browser are in AWS.
If that's your issue, disabling ice-lite (`config.erizo.iceLite = false`) or using nicer (`config.erizo.useNicer = true`) will fix it.

**Comment by ranthwar-vcloudx** [comment]
Thanks for the reply.

We are using latest libNice module along with Trickle set to True..We are using Normal desktop browsers for FF,Safari.

Thanks..Will try those with that options...

Will there be any other issues/side affects if i turned above flags..??

Regards
Ram

**Comment by lodoyun** [comment]
Using ice-lite and libnice helps with an issue that we detected that could cause users to go through TURN unnecessarily. Wether you ever experience that issue depends on your Licode deployment (particularly where your TURN servers are), you may not run into it at all. Other than that, I'm not aware of any other issue with libnice when iceLite is turned off. 
Nicer may be a bit riskier long-term since we're focusing on libnice now and don't plan to actively update Nicer in the future.

**Comment by ranthwar-vcloudx** [comment]
Thanks @lodoyun .

**Pull request merged**
