### PR TITLE
Fix for recording audio and screensharing streams

### PR DESCRIPTION
**Pull request by zafergurel**
**Description**
ExternalOutput does not record audio-only or video-only (screensharing) streams.

The changes introduced in this commit lets ExternalOutput to be aware that the stream is an audio-only or video-only stream.

Also please look at https://github.com/lynckia/licode/pull/1254 .
The comments about this PR made this PR possible.

Issues #1203 and #1185 are related and can be fixed with this PR.

[x] It needs and includes Unit Tests

**Changes in Client or Server public APIs**
ExternalOutput in erizoAPI has been changed. 
A new method named setHasAudioAndVideo has been added to ExternalOutput (ExternalOutput.h and ExternalOutput.cc).

### CODE REVIEW

**Comment by zafergurel** [comment]
I've compiled and tested those changes in this PR.
It works but I don't understand why the tests fail.
Anyone that wants to proceed to solve this recording issue can get an idea how it's done.
I won't try more to get this PR passing the tests.

**Comment by nvazquezg** [comment]
@zafergurel I've made a PR in your fork that should pass the tests: https://github.com/advancity/licode/pull/2

**Comment by nvazquezg** [comment]
@zafergurel I found no problems with the recordings of video-and-audio streams and audio-only streams, there is also no delay in the start of the recording :+1: 

But the screen (video-only) is not working in my tests:

The logs show:
`media.ExternalOutput - hasVideo_: 1 hasAudio_: 1 video_codec_: 141 audio_codec_: 0`

And this makes true this condition, that invalidates the output:
https://github.com/advancity/licode/blob/082fc5eed4ffd227cc39402693e28ff9c7bb8d8a/erizo/src/erizo/media/ExternalOutput.cpp#L389-L391

Any ideas to fix this situation?

**Comment by nvazquezg** [comment]
@zafergurel This problem was in my client side, I was creating the screenshare stream with `audio: true`. Setting `audio:false` in the client side fixed the problem.
I did not find any other problems, so this LGTM. :+1:

**Comment by zafergurel** [comment]
@nvazquezg Very good. :+1:  

> Setting audio:false in the client side fixed the problem

**Comment by zafergurel** [comment]
@nvazquezg I still have missing parts in the recording file. I use the docker container.
Audio is being recorded after some time passes so that the beginning of the audio is missing.
Also, the end of recording is missing. I suspect that the last video frames are not recorded properly when I close my web cam. 
I use windows 8.1 and chrome.
Have you faced those problems? 
With such improper recording, I'm not able to use licode.

**Comment by nvazquezg** [comment]
@zafergurel With your PR, the recordings don't miss any audio or video at the beginning. The last ~5 seconds of the recording are missing, though, but it is close enough for my use case ATM.
I guess it may be related to the output of the last packets remaining when stopping the recording...  

Have you tested this PR? https://github.com/lynckia/licode/pull/1254
And H264? https://github.com/lynckia/licode/pull/1124

**Comment by zafergurel** [comment]
@nvazquezg I have not tested those PRs yet. I'll check them out as soon as I find time.
Thanks for sharing. :+1:

**Comment by nvazquezg** [comment]
@lodoyun @jcague Could you please review and consider merging this PR? It solves #1185 and #1203.

**Comment by ababutski** [comment]
Also waiting for this PR.

**Comment by footniko** [comment]
Any updates on this?

**Comment by footniko** [comment]
This fix still doesn't allow recording with audio enabled :(

**Comment by peererror** [comment]
any update on this pull

**Comment by zafergurel** [comment]
This is fixed by https://github.com/lynckia/licode/pull/1808. So, it's time to close it.

**Pull request closed without merging**
