### PR TITLE
processSignalingMessage executed if stream is local.

### PR DESCRIPTION
**Pull request by simonemazzoni**
Possible fix for [issue #616](https://github.com/lynckia/licode/issues/616)

### CODE REVIEW

**Comment by simonemazzoni** [comment]
Also refer to [https://github.com/lynckia/licode/issues/616#issuecomment-278402223](https://github.com/lynckia/licode/issues/616#issuecomment-278402223) for an explanation of the fix.

**Comment by aalonsog** [comment]
Thanks for the PR. However, I have concerns about this solution. [Here](https://github.com/lynckia/licode/issues/616#issuecomment-278926272) my explanation. If you agree with the workaround I propose, could you implement it?

**Comment by simonemazzoni** [comment]
@aalonsog have you read my comment about this PR? Any news about it?

**Comment by simonemazzoni** [comment]
I updated this pull request according to my discussion with @aalonsog.

Anyway I guess we should continue our discussion about failed streams.

Please, let me know.

**Comment by simonemazzoni** [comment]
I'm going to close this PR since I created it from my master branch and it causes confusion every time I update my master branch.

I'll resend a new PR from a dedicated clean branch.

Sorry about this.

**Comment by aalonsog** [comment]
Ok thanks!

**Comment by simonemazzoni** [comment]
@aalonsog PR already sent!
Please have a look at it and send me some feedback.

**Pull request closed without merging**
